@endpoint = https://kx8bc87mld.execute-api.us-east-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/helloNodeJs
###

GET {{endpoint}}/spaces?spaceId=f87d915e-57bf-458f-8fec-33cd2de58391
###

GET {{endpoint}}/spaces?location=London
###

GET {{endpoint}}/spaces
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
   "location": "Minsk",
   "name": "Park Avenue"
}
###